Repository mitre/heimdall-lite, pull requests merged in 2019-09, with the labels that each got.

#26 STY: Merge style fixes
  src/components/cards/controltable/ControlRowDetails.vue
  src/main.ts
Labels: bug, enhancement

#38 STY: Control details have labels listed above content and add zebra
  package-lock.json
  src/components/cards/controltable/ControlRowDetails.vue
Labels: bug

#45 Chrome code highlighting
  package-lock.json
  package.json
  public/index.html
  src/components/cards/controltable/ControlRowDetails.vue
  src/components/cards/controltable/ControlRowHeader.vue
  src/components/cards/controltable/ControlTable.vue
  src/components/cards/treemap/Treemap.vue
  src/components/generic/ColumnHeader.vue
  src/components/global/Modal.vue
  src/components/global/Sidebar.vue
  src/components/global/UploadNexus.vue
  src/components/global/sidebaritems/SidebarFile.vue
  src/components/global/upload_tabs/FileReader.vue
  src/router.ts
  src/sass/main.scss
  src/views/Landing.vue
  src/views/Results.vue
  vue.config.js
Labels: bug, enhancement

#44 S3 Bucket Support (WIP)
  package-lock.json
  package.json
  public/index.html
  src/components/cards/controltable/ControlRowDetails.vue
  src/components/cards/controltable/ControlRowHeader.vue
  src/components/cards/controltable/ControlTable.vue
  src/components/cards/treemap/Treemap.vue
  src/components/generic/ApexPieChart.vue
  src/components/generic/ColumnHeader.vue
  src/components/global/Modal.vue
  src/components/global/Sidebar.vue
  src/components/global/UploadNexus.vue
  src/components/global/sidebaritems/SidebarFile.vue
  src/components/global/upload_tabs/FileReader.vue
  src/components/global/upload_tabs/S3Reader.vue
  src/router.ts
  src/sass/main.scss
  src/store/README.md
  src/store/color_hack.ts
  src/store/report_intake.ts
  src/utilities/async_util.ts
  src/views/Compare.vue
  src/views/Landing.vue
  src/views/Results.vue
  tsconfig.json
  vue.config.js
Labels: enhancement
