Repository mitre/heimdall-lite, pull requests merged in 2019-11, with the labels that each got.

#157 Lm 149
  src/components/global/AboutModal.vue
  src/components/global/HelpModal.vue
  src/components/global/Sidebar.vue
  src/components/global/UploadNexus.vue
  src/components/global/upload_tabs/HelpFooter.vue
Labels: MEDIUM, enhancement

#180 Docker Support
  .github/workflows/VERSION.yml
  .github_changelog_generator
  CHANGELOG.md
  Dockerfile
  README.md
  VERSION.md
  package-lock.json
  package.json
  public/index.html
Labels: enhancement

#186 Update the Light/Dark UX
  package-lock.json
  package.json
  src/components/global/Sidebar.vue
  src/components/global/Topbar.vue
Labels: enhancement, help wanted
