Repository mitre/heimdall-lite, pull requests merged in 2019-10, with the labels that each got.

#63 Chrome code highlighting final
  src/components/cards/controltable/ControlRowDetails.vue
  src/sass/main.scss
Labels: bug

#74 ENH: Add vue toast support Fix #64 #65
  package-lock.json
  package.json
  src/components/global/upload_tabs/FileReader.vue
  src/plugins/vuetify.ts
  src/store/report_intake.ts
Labels: CRITICAL, enhancement

#55 export caat and modals branch
  package-lock.json
  package.json
  src/assets/control_data.png
  src/assets/data_cards.png
  src/assets/data_table.png
  src/assets/treemap.png
  src/components/global/AboutModal.vue
  src/components/global/ExportCaat.vue
  src/components/global/HelpModal.vue
  src/components/global/Sidebar.vue
  src/components/global/sidebaritems/SidebarLink.vue
  vue.config.js
Labels: CRITICAL, enhancement

#112 adding google analytics functionality
  package-lock.json
  package.json
  src/main.ts
  src/types/vue-analytics.d.ts
  tsconfig.json
Labels: enhancement

#113 Fix #53
  src/components/cards/controltable/ControlRowCol.vue
  src/components/cards/controltable/ControlRowDetails.vue
  src/plugins/vuetify.ts
Labels: MEDIUM, bug

#120 BUG: Fix console.logs on status_color
  src/components/cards/controltable/ControlRowDetails.vue
Labels: bug

#127 BUG: Fix #125 and swap out vue-line-clamp for vue-clamp
  package-lock.json
  package.json
  src/components/cards/controltable/ControlRowCol.vue
  src/components/cards/controltable/ControlRowDetails.vue
  src/plugins/vuetify.ts
Labels: bug

#138 BUG: Fix #137
  src/components/global/HelpModal.vue
Labels: documentation, enhancement

#142 Cleanup for HL2.0
  src/components/cards/StatusCardRow.vue
  src/components/cards/controltable/ControlRowCol.vue
  src/components/cards/controltable/ControlRowDetails.vue
  src/components/cards/controltable/ControlRowHeader.vue
  src/sass/main.scss
Labels: CRITICAL, enhancement

#153 BUG: Fix missing icons in single page builds
  package-lock.json
  package.json
  src/components/global/upload_tabs/FileReader.vue
  src/components/global/upload_tabs/S3Reader.vue
  src/views/Results.vue
  vue.config.js
Labels: bug
