Repository mitre/heimdall-lite, pull requests merged in 2020-08, with the labels that each got.

#293 Fixes #254, #262, #267, #269
  src/components/generic/ErrorTooltip.vue
  src/components/global/UploadNexus.vue
  src/components/global/upload_tabs/aws/S3Reader.vue
  src/components/global/upload_tabs/splunk/SplunkReader.vue
  src/plugins/vuetify.ts
  src/sass/main.scss
Labels: bug, enhancement

#321 Snackbar fix
  src/views/Results.vue
Labels: bug

#322 Profile info fix
  src/views/Results.vue
Labels: bug

#333 Broken Link and Autodate on Footer
  package.json
  src/components/global/Footer.vue
  src/components/global/upload_tabs/HelpFooter.vue
Labels: documentation, enhancement
